### ISSUE TITLE
Allow downgrading packages

### ISSUE THREAD

**Issue by steelcowboy** [facebookincubator/go2chef#35]
Because Go2Chef does not allow downgrading, it alone does not help in a scenario where it might install a stable version of Chef and you'd want it to recover if a later version of Chef caused an issue.

For instance, Chef 15.6 works with our current code and Chef 16.2 doesn't. We can't use Go2Chef to get back to Chef 15.6 without first uninstalling Chef 16.2. There should be some kind of option, such as "allow_downgrade", in the config that enables this kind of functionality.

**Comment by oko** [comment]
@steelcowboy have you tried with the RPM plugin? should be doable to add `--allow-downgrade` as an option that can be enabled for the `yum` and `dnf` plugins, but I'm not sure if `rpm -Uvh` (the command that the `rpm` mode executes) does any downgrade checks or not.

**Comment by steelcowboy** [comment]
`rpm -Uvh` does not allow downgrades unfortunately. I suggest adding `--oldpackage` to the command line, as then its behavior will mirror `dnf install` when a version is specified.
