### ISSUE TITLE
[Issue] Add Makefile entry for Apple Silicon

### ISSUE THREAD

**Issue by jkjetty** [facebookincubator/go2chef#55]
It would be nice to have an easy Makefile entry for M1 and newer Macs. 

I'm happy to do this and test it. Should we call it `darwin-apple-silicon` or `darwin-arm` or `darwin-arm64`?

**Comment by oko** [comment]
`darwin-arm64` is most consistent with Go's `GOOS` and `GOARCH` concepts, prefer that.

**Comment by jkjetty** [comment]
Ah my bad I just discovered that `darwinARM` does exist in the Makefile already.
